Add schemas attribute to Schema type
elimity-com/scim pull request #139
Opened 2022-01-17 17:13 UTC by hrenard

Hi,
I'm new to SCIM, and I'm trying to build a Service Provider compatible with https://github.com/suvera/keycloak-scim2-storage.
I encountered an error, the Schema type has no `schemas` attribute wich I think is mandatory because of this section : https://datatracker.ietf.org/doc/html/rfc7643#section-3.

2022-01-18 19:31 UTC, di-wu reviewed
Hi @hrenard! Thank you for opening the PR and getting involved. 💯 

Do you have more documentation or examples/tests that cover this case?

The `schema` type is not a default SCIM resource, it is described in [RFC7643 Section 7](https://datatracker.ietf.org/doc/html/rfc7643#section-7). So I think does not need a `schemas` field (open for discussion of course).

2022-01-18 21:03 UTC, hrenard commented
Sorry, I don't have more examples.

But, in [RFC7643 Section 7](https://datatracker.ietf.org/doc/html/rfc7643#section-7) :
> These resources have a "schemas"
   attribute with the following schema URI:
   urn:ietf:params:scim:schemas:core:2.0:Schema
  
  The `urn:ietf:params:scim:schemas:core:2.0:Schema` would serve no purpose if not attached to schemas definitions, don't you think ?
Also, the `schemas` field isn't stated explicitly in all [RFC7643 Section 4](https://datatracker.ietf.org/doc/html/rfc7643#section-4) but required because of [RFC7643 Section 3](https://datatracker.ietf.org/doc/html/rfc7643#section-3).

Am I consistent ? I'm not a native English speaker, so I can miss subtleties.

2022-01-19 07:19 UTC, di-wu commented
No, it makes sense to add it!

2022-01-19 07:20 UTC, di-wu requested changes
LGTM.

Can you fix the tests?
I think you just need to add the `schemas` field to the files in `schema/testdata`.

2022-01-20 05:42 UTC, di-wu approved these changes

2022-01-20 05:42 UTC, merged